name: Test Package Install with Pip

on:
  push:
    branches:
      - master
      - test-pip-gaction

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install C++ dependencies
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install with pip
      run: |
        pip install .
